export type Magnet = {
  slug: string;
  kw: string;
  title: string;
  url: string;
  /** Page h1 + meta title. Default: "Your free {title}". */
  heading?: string;
  /** Line under the h1. Default: the guide blurb. */
  blurb?: string;
  /** Button text after signup. Default: "Open the guide →". */
  cta?: string;
  /** Submit button text: what they get. Default: "Send it". */
  button?: string;
  /** Show /get/{slug}.jpg (first page of the guide) as proof. Default: true. */
  preview?: boolean;
  /** Hide the "See the Reel Kit" line after signup. */
  hideKitLine?: boolean;
  /** Loops userGroup. "deal" keeps sales leads out of the "IG lead nurture" workflow (filter userGroup = lead). Default: "lead". */
  group?: "deal";
};

/** Instagram comment->DM lead magnets. Source: kaiship-business magnets.json. */
export const magnets: Magnet[] = [
  { slug: "skills", kw: "SKILLS", title: "3 starter skills", url: "https://9mnakwbq5fbjl7jj.public.blob.vercel-storage.com/free/kaiships-starter-skills-v1-Bk0J6qtX1iJhoJLGz22Su8WnYyKYN8.zip", heading: "3 free Claude Code skills to run your business", blurb: "Weekly review, free-guide page builder and demand check: 3 of the 9 skills I use to run kaiships.ai. Drop your email and the zip downloads right here.", cta: "Download the 3 skills →", button: "Send me the skills", preview: false },
  { slug: "gear", kw: "GEAR", title: "4 setup plugins", url: "https://kai-ships-ai-website.vercel.app/free/gear.html", heading: "4 free plugins to set up Claude Code", blurb: "Memory between sessions, a skill finder, a document reader and Anthropic's own setup advisor, each with its install command. Drop your email and it opens right here.", button: "Send me the 4 plugins", preview: false },
  { slug: "vibe", kw: "VIBE", title: "5 vibe coding plugins", url: "https://kai-ships-ai-website.vercel.app/free/vibe.html", heading: "5 plugins for vibe coding with Claude Code", blurb: "A browser your AI can test in, a database it can manage, a security tester, a design copier and fresh docs, each with its install command. Drop your email and it opens right here.", button: "Send me the 5 plugins", preview: false },
  { slug: "audit", kw: "AUDIT", title: "Prompt audit", url: "https://docs.google.com/document/d/1YJ1zVzP6Pvr3GidN0z6g6DQpdcsB2AEjLRjJGaQFb2E/view", heading: "Find what's out of date in your CLAUDE.md", blurb: "Anthropic's own audit command for Opus 5.5: how to install it, run it, and read the report. Drop your email and it opens right here.", button: "Send me the audit steps" },
  { slug: "open", kw: "OPEN", title: "OpenAlternative", url: "https://docs.google.com/document/d/1cUu4SbGTP6KYhTCH6ZKImRHbJk--RgdusGypZrbZOk4/view", heading: "Stop paying for tools that have free open-source versions", blurb: "The site from the reel, plus open-source swaps for Cursor and 4 more paid tools, and what you give up. Drop your email and it opens right here.", button: "Send me the list" },
  { slug: "prompt", kw: "PROMPT", title: "prompts.chat", url: "https://docs.google.com/document/d/16QKgLUcjD0CfCQVecbM4YzEhlLbYdg9I3P9VIWKs0wg/view", heading: "Plug a 170k-star prompt library into Claude Code", blurb: "The links, the one-line install, and what to ask it. Free to use, paid work included. Drop your email and it opens right here.", button: "Send me the install" },
  { slug: "senior", kw: "SENIOR", title: "Agent Skills", url: "https://docs.google.com/document/d/1eCcDMNIoHz6eZDYBpgzCE7RAHujHwGCdZvdCmVkDAdI/view", heading: "Give your coding agent senior-engineer habits", blurb: "Addy Osmani's 25 free skills: spec, plan, build, test, review, ship. The install and a first run you can do tonight. Drop your email and it opens right here.", button: "Send me the install" },
  { slug: "limit", kw: "LIMIT", title: "4 usage-limit tools", url: "https://docs.google.com/document/d/1PuxzdVkYW_VrOQ-LDnWanG_VZQhyDte3SzH4W9azgoM/view", heading: "Stop Claude Code hitting its limit mid-task", blurb: "4 free tools: see where your tokens go, then cut the waste. Install commands from each README. Drop your email and it opens right here.", button: "Send me the 4 tools" },
  { slug: "scrape", kw: "SCRAPE", title: "3 scraping tools", url: "https://docs.google.com/document/d/1hWd3nO1TH6MOxGb4YiIZUBWO_Ovgbe_I5wdczvYFeZM/view", heading: "Let Claude Code read any website", blurb: "3 open-source scrapers, the setup commands, and what each one costs to run. Drop your email and it opens right here.", button: "Send me the 3 tools" },
  { slug: "income", kw: "INCOME", title: "4 service repos", url: "https://docs.google.com/document/d/1csaUiVsjcJ1tG9VkthDo3S7Zfc_C35xaLCavEc9QeLI/view", heading: "4 free repos you can turn into a small AI service", blurb: "What each one does, a service idea to test, the licence in plain words, and the start command. Drop your email and it opens right here.", button: "Send me the 4 repos" },
  { slug: "api", kw: "API", title: "Free AI API list", url: "https://docs.google.com/document/d/1CddyELg8qpLFr8lZg2dTTMUe1UWx-z-ohFn7WO7VPXU/view", heading: "Build with AI APIs without paying for tokens", blurb: "A list of 16 providers with a permanent free tier, and the 4 I'd try first. Drop your email and it opens right here.", button: "Send me the list" },
  { slug: "repos", kw: "REPOS", title: "4 design repos", url: "https://docs.google.com/document/d/1yYawdzkUnvSajMIguN17NUOrJO-4sGYpZReihLViJdY/view", heading: "Make your site look expensive with 4 free repos", blurb: "Each one with its install command and a prompt to paste into Claude Code. Drop your email and it opens right here.", button: "Send me the 4 repos" },
  { slug: "stack", kw: "STACK", title: "AI tool stack", url: "https://docs.google.com/document/d/1vV8aVDThatWyqMx_9GUiS3XhIlXEClmHRwNEe_BDerI/view", heading: "The one AI tool I'd use for each of 6 jobs", blurb: "Writing, research and 4 more: three tools per job, and the one I'd pick. Drop your email and it opens right here.", button: "Send me the stack" },
  { slug: "sonnet", kw: "SONNET", title: "Which Claude cheat sheet", url: "https://docs.google.com/document/d/14CADI_1mycKoCNwsywbgs_PGTJLOHS3IPArNWLGJ5Jk/view", heading: "Know which Claude to use, every time", blurb: "One page: Sonnet 5.5 or Opus 5.5 for each kind of task, and why. Drop your email and it opens right here.", button: "Send me the cheat sheet" },
  { slug: "google", kw: "GOOGLE", title: "15 Google AI tools", url: "https://docs.google.com/document/d/1BfQ57l6npagzcCvpaQHQd0andzhLDDsFr8jCjazpfCk/view", heading: "15 free Google AI tools most people haven't tried", blurb: "The 5 from the reel plus 10 more, each with what it does and whether it's free. Drop your email and it opens right here.", button: "Send me the 15 tools" },
  { slug: "apple", kw: "APPLE", title: "Apple design skill", url: "https://docs.google.com/document/d/1-rQAITnIPu3PK5QcEFGinThVmzpLpSQMy7GHpLwbKv0/view", heading: "Make Claude design like Apple", blurb: "A free skill that turns Apple's fluid-interface rules into web code: springs, spacing, restraint. Install steps included. Drop your email and it opens right here.", button: "Send me the skill" },
  { slug: "frontend", kw: "FRONTEND", title: "5 frontend plugins", url: "https://docs.google.com/document/d/1ffMhTUVEFRlfMAdqpp07gRaHUe5ba9cSG8LW3qepvAQ/view", heading: "Stop Claude's UI from looking vibe-coded", blurb: "5 plugins for better front-end design, with the install command for each. Drop your email and it opens right here.", button: "Send me the 5 plugins" },
  { slug: "effort", kw: "EFFORT", title: "Effort cheat sheet", url: "https://docs.google.com/document/d/1L_H-sULYJEXkR2ocAfmztiQMkHvrQ43VTYk9I2aPJ5k/view", heading: "Know which effort setting to use for each job", blurb: "A one-page cheat sheet built on the Claude Code team's own guide to effort. Drop your email and it opens right here.", button: "Send me the cheat sheet" },
  { slug: "coding", kw: "CODING", title: "4 vibe plugins", url: "https://docs.google.com/document/d/1COe3DX17s28oRRF2IRh0tZ42c1gJSEd_YMQ6DK1gvZA/view", heading: "4 plugins to install before you vibe code", blurb: "What each one does, the exact install command, and the link. Drop your email and it opens right here.", button: "Send me the 4 plugins" },
  { slug: "die", kw: "DIE", title: "Web design setup", url: "https://docs.google.com/document/d/1ehxOBkuk_Ygja2CABx80MiCcQV4KqbaAdWaloquRixE/view", heading: "The Claude setup I use to build good-looking sites", blurb: "Every tool from the reel, how to install each one, and a first site to try them on. Drop your email and it opens right here.", button: "Send me the setup" },
  { slug: "claude", kw: "CLAUDE", title: "5 Claude Code plugins", url: "https://drive.google.com/file/d/12KGukRg9I29SgUTzY6ValGgVqpEm6XNh/view?usp=sharing", heading: "5 plugins to install before you touch Claude Code", blurb: "GitHub links and a one-line install for each. Set up in under 5 minutes. Drop your email and it opens right here.", button: "Send me the 5 plugins" },
  { slug: "design", kw: "DESIGN", title: "5 Claude design plugins", url: "https://drive.google.com/file/d/1ZYRCCVYhrx0w6E2ctW6H211-8mdox9CF/view?usp=sharing", heading: "5 plugins that give Claude real design taste", blurb: "One line on what each does, and its link. Drop your email and it opens right here.", button: "Send me the 5 plugins" },
  { slug: "skill", kw: "SKILL", title: "Agent Reach guide", url: "https://kai-ships-ai-website.vercel.app/ig/agent-reach-guide/slide1.pdf", heading: "Give your AI agent eyes on the whole internet", blurb: "Agent Reach: one CLI, zero API keys. Works with any agent that can run a shell command. Drop your email and it opens right here.", button: "Send me the guide" },
  { slug: "tools", kw: "TOOLS", title: "AI Tools List", url: "https://kai-ships-ai-website.vercel.app/ig/sunday-content-engine/slide1.pdf", heading: "Turn one Sunday evening into a week of reels", blurb: "The 4-tool stack, 3 copy-paste prompts, and the timed routine. Drop your email and it opens right here.", button: "Send me the playbook" },
  { slug: "frame", kw: "FRAME", title: "Reel Kit", url: "https://buy.polar.sh/polar_cl_HyrrBG3sH6HuMBa6QZndeGTLHaaErzsyHqZwG0sl3bV?utm_source=ig_dm&utm_medium=social&utm_campaign=frame", heading: "Reel Kit launch price", blurb: "Reel Kit ($50) + Token Diet bonus → $29.99 till Oct 9. Token Diet = my 2-page notes on spending fewer tokens. Drop your email and the checkout opens right here.", cta: "Get the Reel Kit · $29.99 →", button: "Show me the price", hideKitLine: true, preview: false, group: "deal" },
  { slug: "kit", kw: "KIT", title: "Reel Kit", url: "https://buy.polar.sh/polar_cl_HyrrBG3sH6HuMBa6QZndeGTLHaaErzsyHqZwG0sl3bV?utm_source=ig_dm&utm_medium=social&utm_campaign=kit", heading: "Reel Kit launch price", blurb: "Reel Kit ($50) + Token Diet bonus → $29.99 till Oct 9. Token Diet = my 2-page notes on spending fewer tokens. Drop your email and the checkout opens right here.", cta: "Get the Reel Kit · $29.99 →", button: "Show me the price", hideKitLine: true, preview: false, group: "deal" },
  { slug: "learn", kw: "LEARN", title: "vibe-wise", url: "https://github.com/nykooi1/vibe-wise", blurb: "Drop your email and the repo opens right here. I'll also send you the next ones I make.", cta: "Open the repo →", button: "Send me the repo", preview: false },
];

export const getMagnet = (slug: string) => magnets.find((m) => m.slug === slug);
